### PR TITLE
Convert the async mount and umount methods to nan so it works with node ...

### PR DESCRIPTION
**Pull request by netlovers**
No sync versions, and we still have to figure out what to do with the `strerror()`, because it is not the expected node error message just something similar. But I'm not sure how `node::ErrnoException` can be used in the async methods.

### CODE REVIEW

**Comment by netlovers** [comment]
By the way, looking at the `mount.js` file the coding style should be standardized too. Maybe using http://editorconfig.org/ and some conventions for example the indent style: http://en.wikipedia.org/wiki/Indent_style
Right now it is half allman, half something else.

**Comment by piranna** [comment]
In the Javascript file I've left as they were the parts that I didn't modified, so that's the reason of the mixed style (4 spaces? brrr...).

Just curious, why did you removed the sync methods? Were they giving you problems, or just to simplify the API?

**Comment by netlovers** [comment]
Just to simplify the API. And getting the error messages to work in the async versions made me frustrated, so I didn't even try to convert the sync versions. But we can add those later, if they are needed for something.

**Comment by piranna** [comment]
Ok, just to know it :-) Now I'll need to update the other projects :-P

**Pull request merged**
